apiVersion: v1
kind: Service
metadata:
  name: capstoneproject-service
spec:
  selector:
    app: financeproject
  ports:
    - protocol: TCP
      port: 80 # Port that the service exposes
      targetPort: 8081 # Port on the container
      nodePort: 31000 # Choose a valid port within the range 30000-32767
  type: NodePort
